config/routes.rb
Myapp::Application.routes.draw do

  root 'students#index'
  resources :students

  resources :phone_numbers, only: [:new, :create]
post 'phone_numbers/verify' => "phone_numbers#verify"

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
	def generate_pin
	  self.pin = rand(0000..9999).to_s.rjust(4, "0")
	  save
	end

	def twilio_client
	  Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
	end

	def send_pin
		twilio_client.messages.create(
		    to: phone_number,
		    from: ENV['TWILIO_PHONE_NUMBER'],
		    body: "Your PIN is #{pin}"
		)
	end

	def verify(entered_pin)
	  update(verified: true) if self.pin == entered_pin
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
	def new
	  @phone_number = PhoneNumber.new
	end
	def create
		@phone_number = PhoneNumber.find_or_create_by(phone_number: params[:phone_number][:phone_number])
		@phone_number.generate_pin
		@phone_number.send_pin
		respond_to do |format|
			format.js # render app/views/phone_numbers/create.js.erb
		end
	end
	def verify
		@phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])
		@phone_number.verify(params[:pin])
		respond_to do |format|
		    format.js
		end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def default_url_option

	

	end

	def index
		@student = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end


	def new
		@student = Student.new
	end


	def create
		@student = Student.create(student_params)
		if @student.save
			redirect_to @student
		else
			redirect_to new
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])

        if @student.update(student_params)
			redirect_to "/students"
		else
			flash.now[:error] = "Could not save client"
			redirect_to "/students"
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to "/students"
	end

	def student_params
		params.require(:student).permit(:name, :roll_no, :city, :gender, :description, :phno)	
	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phone_numbers/create.js.erb
$('#hidden_phone_number').val('<%= @phone_number.phone_number %>' )
$('#send-pin').hide()
$('#verify-pin').fadeToggle()
$('#pin').focus()

app/views/phone_numbers/new.html.erb
<div id="send-pin">
  <h3>What's your phone number?</h3>
  <%= form_for @phone_number, remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :phone_number %>
    </div>
    <%= f.submit "Send PIN", class: "btn btn-primary", id: 'send-pin-link' %>
  <% end %>
</div>
<div id="verify-pin">
  <h3>Enter your PIN</h3>
  <%= form_tag phone_numbers_verify_path, remote: true do |f| %>
    <%= hidden_field_tag 'hidden_phone_number', '' %>
    <div class="form-group">
      <%= text_field_tag :pin %>
    </div>
    <%= submit_tag "Verify PIN", class: "btn btn-primary" %>
  <% end %>
</div>
 
<div id="status-box" class="alert alert-success">
  <p id="status-message">Status: Haven’t done anything yet</p>
</div>

app/views/phone_numbers/verify.js.erb
<% if @phone_number.verified %>
	$('#verify-pin').hide()
	$('#status-box').removeClass()
	$('#status-box').addClass('alert alert-success')
	$('#status-message').text('Success!!')
<% else %>
	$('#status-box').removeClass()
	$('#status-box').addClass('alert alert-warning')
	$('#status-message').text("Sorry, that wasn't the right pin.")
<% end %>
$('#status-box').fadeToggle()

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  Name:           <%= f.text_field :name %><br/>
  Roll number:    <%= f.text_field :roll_no %><br/>
  City:           <%= f.text_field :city %><br/>
  Gender:         <%= f.select :gender, options_for_select(["Select One", "Male", "Female"],              :disabled => ["Select One"]) %><br/>

  Description:    <%= f.check_box :description, {:multiple => true}, "CSE", nil  %> 
                  <%= f.check_box :description, {:multiple => true}, "ECE", nil %> 
                  <%= f.check_box :description, {:multiple => true}, "EE", nil %>
                  <%= f.check_box :description, {:multiple => true}, "MECHANICAL", nil %>

<!-- <input type="checkbox" name="student[description]" value="cse">CSE
<input type="checkbox" name="student[description]" value="ece">ECE
<input type="checkbox" name="student[description]" value="ee">EE
<input type="checkbox" name="student[description]" value="mec">MECH -->


  Photo:          <%= f.file_field :photo %><br/>
  Phone number:   <%= f.text_field :phno %><br/>
  <%= submit_tag("Submit") %> 

<% end %>

app/views/students/edit.html.erb
<%= render :partial => "form" %>

app/views/students/index.html.erb
<h1  align="center">STUDENT RECORDS</h1>
<table border="1" , align="center">
<tr><th>NAME</th>
    <th >ROLL NUMBER</th>
    <th>CITY</th>
    <th colspan="3">GENDER</th>
</tr>
<% @student.each do |obj| %>
<tr><td><%=obj.name%></td>
    <td><%=obj.roll_no%></td>  
    <td><%=obj.city%></td> 
    <td><%=obj.gender%></td>
    <td><%= link_to 'EDIT', "/students/#{obj.id}/edit" %></td>
    <td><%= link_to 'DELETE', "/students/#{obj.id}", method: :delete , :confirm => "Are you sure you want to delete this item?"  %></td>
</tr>
<%end%>
</table>
<br/><br/><br/>
<h2 align="center"><%= link_to 'New record', new_student_path %></h2>
<%= image_tag "app/assets/images/index.jpeg", alt: "Home" %>

app/views/students/new.html.erb
<%= render :partial => "form" %>

app/views/students/show.html.erb
<table border="1">

	 <tr>
		  <th>student name</th>		
		  <th>roll number</th>
          <th>city</th>
          <th>gender</th>
          <th>descritpion</th>
	 </tr>
	 <tr>
		  <td><%= @student.name %> </td>
		  <td><%= @student.roll_no %> </td>	
          <td><%= @student.city %></td>
          <td><%= @student.gender %></td>
          <td><%= @student.description %></td>
	 </tr>

</table>
<%= @student.photo%>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>